#nopain lists the blocks that, when placed, won't cause an injury. If you need to know how to write it, install my other plugin Ouch and place the block.
#damage is how much it'll take off (x2) 4 = 2 hearts
#chanceofhurt - if the random number it makes is higher than chanceofhurt, it does the damage. 80 is 1-in-5.
nopain: torch, sign, 
damage: 4
chanceofhurt: 80